### ISSUE TITLE
Add null checks for user members when updating entity

### ISSUE THREAD

**Issue by Geanik** [Geanik/user-session-backend#2]
When calling the update query with an UserDto that has null members, the nulls get sent to DB.
Change this behaviour to only update fields that have changed and are not null.

**Comment by HatboyWonder** [comment]
I can take a look at that

**Comment by HatboyWonder** [comment]
**pls assign to me**

**Comment by Geanik** [comment]
thank you hatboy

you can find the concerning code at com.geanik.user_session_backend.logic.BusinessLogicImpl#updateUser
